services:
  api.directus:
    image: directus/directus:latest
    container_name: api-directus-geoquizz
    env_file:
      - ./back/app-directus/directus-api.env
    depends_on:
      directus.db:
        condition: service_healthy
    ports:
      - "33556:8055"
    networks:
      - geoquizz-network
  directus.db:
    image: postgres:latest
    container_name: db-directus-geoquizz
    volumes:
      - ./back/app-directus/data:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root", "-d", "directusdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    env_file:
      - ./back/app-directus/directus-db.env
    networks:
      - geoquizz-network

  adminer:
    image: adminer
    container_name: adminer-geoquizz
    ports:
      - '8080:8080'
    networks:
      - geoquizz-network

networks:
  geoquizz-network:
    driver: bridge